### ISSUE TITLE
docs: Add AWS-LearningResource to Extra Content table

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#106]
Add https://github.com/tungbq/AWS-LearningResource to this table:
https://github.com/tungbq/devops-basic#extra-content-from-other-repos

**Comment by dcompanykrish** [comment]
AWS Learning Resource has been added to content table, please check and review my PR

**Comment by tungbq** [comment]
> AWS Learning Resource has been added to content table, please check and review my PR

Thank you, please check my comment
