### ISSUE TITLE
docker: Add docker cheatsheet link

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#133]
Append these line to the end of https://github.com/tungbq/devops-basic/tree/main/topic/docker#readme:
```
# Docker cheatsheet
- https://docs.docker.com/get-started/[docker_cheatsheet.pdf](https://docs.docker.com/get-started/docker_cheatsheet.pdf)
```

**Comment by dcompanykrish** [comment]
I have appended the lines to the end of the README.md file on GitHub. You can check the updated file here: [https://github.com/tungbq/devops-basic/tree/main/topic/docker#readme]. Thank you for your guidance.

**Comment by tungbq** [comment]
This issue is resolved. Closing
