### ISSUE TITLE
jenkins: add example pipeline to run 2 stages in parallel

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#241]
**Pipeline script location:** https://github.com/tungbq/devops-basic/tree/main/topics/jenkins/helloworld
**DoD:**
- Similar to the current example: https://github.com/tungbq/devops-basic/blob/main/topics/jenkins/helloworld/MyFirstPipeline.groovy
- Create the new file `PipelineWithParralellStages.groovy` (or you can propose a better name with similar meaning to that one)
- Add example pipeline to run 2 stages in parallel
- The example pipeline could be simple, no need too complicated (just print message is acceptable)
- New pipeline works fine on Jenkins

**Comment by dcompanykrish** [comment]
I'm happy to report that I have completed the following tasks:

Created a new pipeline script file called PipelineWithParallelStages.groovy in the https://github.com/tungbq/devops-basic/tree/main/topics/jenkins/helloworld directory. 🚀
Added an example pipeline to the file that runs two stages in parallel, ParallelStage1 and ParallelStage2. 👯‍♀️
Each stage simply prints a message to the console. 🗣️
Tested the new pipeline script on Jenkins and confirmed that it works fine. ✅
Please let me know if you have any questions or feedback.

**Comment by tungbq** [comment]
> I'm happy to report that I have completed the following tasks:
> 
> Created a new pipeline script file called PipelineWithParallelStages.groovy in the https://github.com/tungbq/devops-basic/tree/main/topics/jenkins/helloworld directory. 🚀 Added an example pipeline to the file that runs two stages in parallel, ParallelStage1 and ParallelStage2. 👯‍♀️ Each stage simply prints a message to the console. 🗣️ Tested the new pipeline script on Jenkins and confirmed that it works fine. ✅ Please let me know if you have any questions or feedback.

Wao!! I really happy and appreciated for your effort on this repository.
I'll review all of your PR now. Thanks a lot 😍
