### ISSUE TITLE
jenkins: naming the jenkins docker compose stack

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#274]
Task: Name the docker compose stack as `jenkins`

- Docker compose file: https://github.com/tungbq/devops-basic/blob/main/topics/jenkins/deploy/docker-compose/docker-compose.yml
- For now it uses the default name:
  ![image](https://github.com/tungbq/devops-basic/assets/85242618/4f049a57-0824-42d3-aa36-b08639062607)

- Reference: https://stackoverflow.com/a/72412046
- Example:
```
version: "3.9"
name: my-project-name
services:
  myService:
    ...
```

**Comment by dcompanykrish** [comment]
@tungbq ,I have renamed the  Docker Compose stack to jenkins .
Please merge this PR at your convenience. Thank you for your time and feedback!

**Comment by tungbq** [comment]
> @tungbq ,I have renamed the Docker Compose stack to jenkins . Please merge this PR at your convenience. Thank you for your time and feedback!

Thanks @dcompanykrish
