### ISSUE TITLE
doc: Remove all the green checkmark ✔️ in the Content column

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#280]
Remove all the green checkmark ✔️ in the Content column as below:
![image](https://github.com/tungbq/devops-basic/assets/85242618/af089937-192a-4596-b3b8-51df476c99fe)

Full README.md file could be found at: https://github.com/tungbq/devops-basic/blob/main/README.md

**Comment by dcompanykrish** [comment]
Hello, I’m interested in working on this issue 😊. Is it still available? If so, could you please assign it to me 🙋‍♂️ and   Thank you  🙏.

**Comment by tungbq** [comment]
Sure! Thank you so much @dcompanykrish

**Comment by dcompanykrish** [comment]
🙋‍♂️ I'm excited to see this PR merged. It will make the README.md file much cleaner and easier to read.
