### ISSUE TITLE
ci: add pretty icon 🎉 to the first issue greeting message

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#283]
ci: add pretty icon 🎉 to the first issue greeting message:
- https://github.com/tungbq/devops-basic/blob/b33936990d2d21c4cf5fdbf4ea5497ae398c94a5/.github/workflows/greeting.yml#L22

**Comment by dcompanykrish** [comment]
Hello, I’m interested in working on this issue 😊.could you please assign it to me 🙋‍♂️ and Thank you 🙏
