### ISSUE TITLE
[shell] Write an example to list all current txt file in given foler and save result to another txt

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#29]
Under example folder of shell (https://github.com/tungbq/devops-basic/tree/main/shell/examples), create new bash script:
- to list all current txt file
- then save the result to another txt file
You are free to choose the filename

**Comment by Harshal662** [comment]
please assign it to me

**Comment by tungbq** [comment]
Sure @Harshal662. Assigned it to you now

**Comment by Harshal662** [comment]
added it at grep-command branch

**Comment by tungbq** [comment]
> added it at grep-command branch

Thanks @Harshal662, but I suggest using separated branch for each task. With this, we could update/review and track them separately

**Comment by Harshal662** [comment]
okay

**Comment by tungbq** [comment]
Please check https://github.com/tungbq/devops-basic/blob/main/CONTRIBUTING.md#proposing-changes for more details.

**Comment by Harshal662** [comment]
should i edit readme file in examples folder explaining what is the code

**Comment by tungbq** [comment]
> should i edit readme file in examples folder explaining what is the code

Yes, it would be great. Please process
