### ISSUE TITLE
[shell] Add pretty icon to switch case example

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#31]
In the switch case example: https://github.com/tungbq/devops-basic/blob/4ad55a6ab16920bcda430d1456013221d2f20e9d/shell/basic.sh#L36
Make the example more colorful by adding icon to the fruit:
- For example `echo "You entered apple."` -> to be changed to   `echo "You entered  🍏."`

**Comment by Harshal662** [comment]
I can do that. If we gave apple icon (hard code it) it will print apple icon.

**Comment by tungbq** [comment]
Assigned to you @Harshal662, feel free to propose the PR. Thanks!
