### ISSUE TITLE
[ci] Add shell check workflow for shell folder

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#32]
It's good if we could develop a workflow for checking `shell `script under shell folder https://github.com/tungbq/devops-basic/tree/main/shell
It could be run on every PRs that needs to merge onto main branch and contains change in the `shell `folder

Reference: We could investigate this checker https://github.com/marketplace/actions/shellcheck

**Comment by tungbq** [comment]
Thanks @gaus07 for your willing to help on this issue! Currently we dont have the auto assign feature on this repo, so I assigned it to you manually.

**Comment by gaus07** [comment]
@tungbq I have created a PR in which I made a workflow which will show all the errors and warnings of .sh files. is that it or I have to do something more ?

**Comment by tungbq** [comment]
Thanks @gaus07 for your contribution. It's a very good work, appreciated it!

**Comment by tungbq** [comment]
@gaus07 the next step would be fixing all the error on the shell check results. This will be covered in other separated tasks.
Since there has a lot of errors, I think it's better if we device them by component
![image](https://github.com/tungbq/devops-basic/assets/85242618/908e7b86-86a4-49ca-9d94-8c2f4b7e6871)
For example git, k8s,... each of component should have separated issues to track and fix.

We need contribution on this as well. So, feel free to open the issue to fix this if you are willing to, thanks!
