### ISSUE TITLE
[shell] Add a simple example for grep command in bash script

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#33]
In https://github.com/tungbq/devops-basic/blob/4ad55a6ab16920bcda430d1456013221d2f20e9d/shell/basic.sh#LL52C1-L52C1
Let's add a simple `grep `example to demonstrate how it works. You are free to choose the data to be grepped (may be from a string, or an output from another command)

Reference: https://www.digitalocean.com/community/tutorials/grep-command-in-linux-unix

**Comment by Harshal662** [comment]
Please assign it to me. But I have to add a sample file file in the directory to show that how "grep" command works

**Comment by tungbq** [comment]
Sure, thanks @Harshal662. Feel free to propose the files and location, as long as they are located under `shell ` (https://github.com/tungbq/devops-basic/tree/main/shell) folder

**Comment by tungbq** [comment]
Thanks @Harshal662!
