### ISSUE TITLE
Improve the terraform link in README.md

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#342]
Improvement for https://github.com/tungbq/devops-basic/tree/main/topics/terraform#readme

Current link:
```
# Looking for a Terraform sample project with best practice?
- Check out: https://github.com/tungbq/terraform-sample-project
```
We need to change it to:
```
# Looking for a Terraform sample project with best practice?
- Check out: [terraform-sample-project](https://github.com/tungbq/terraform-sample-project)
```

**NOTE:** This issue is opened for first contributor of this project only

**Comment by PraveenShinde3** [comment]
Can you please assign issue #342 to me? I'd like to take on this task

**Comment by tungbq** [comment]
Sure, thanks @PraveenShinde3 welcome to the repo

**Comment by tungbq** [comment]
@all-contributors please add @PraveenShinde3 as code
