### ISSUE TITLE
bug: fix broken link in docker architecture

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#368]
There has a broken link in: https://github.com/tungbq/devops-basic/tree/main/topics/docker#docker-architecture
![image](https://github.com/tungbq/devops-basic/assets/85242618/ddeb326c-5044-4690-9bcd-31b2cc01d907)

Replace by the new URL: https://docs.docker.com/get-started/overview/#docker-architecture

**Comment by zitaker** [comment]
I'm working on it

**Comment by tungbq** [comment]
Thanks @zitaker assigned it to you

**Comment by tungbq** [comment]
Fixed in #370  by @zitaker. Thanks so much
