### ISSUE TITLE
python: Add a new example to call API using python

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#382]
Add a new example to call API using python.
Write a script to do following tasks:
- Send get API request to https://api.adviceslip.com/advice (to get random advice)
- Print the random advice result to console
- Ensure to have error handling and show status code when error happens
- Add the new example to the list https://github.com/tungbq/devops-basic/tree/main/topics/python/examples

The script should be located at https://github.com/tungbq/devops-basic/tree/main/topics/python/examples

Similar to task #379 
NOTE: This issue is open for first timer contributor to this repository only

**Comment by mukulbindal** [comment]
!assign

**Comment by tungbq** [comment]
Sure @mukulbindal, welcome to the repository
