### ISSUE TITLE
doc: Fix typo in ansible readme content

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#399]
Typo found in: https://github.com/tungbq/devops-basic/tree/main/topics/ansible#ansible-helloword-
![image](https://github.com/tungbq/devops-basic/assets/85242618/dcbf48e2-0a3f-495d-83da-15a7f6f1ff06)

NOTE: This issue is opened for first timer contributor only. Thanks

**Comment by KatieChilds** [comment]
Hi - this is my first time trying to contribute to an open source project and I was wondering if this issue can still be worked on? Is there anything more I need to know about the project before I get started? Thanks!

**Comment by tungbq** [comment]
Hello @KatieChilds thanks for your interest to this repository contribution!
Yes you can work on this issue.
To get start you could refer to https://github.com/tungbq/devops-basic/blob/main/CONTRIBUTING.md
