### ISSUE TITLE
packer: typo in README.md

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#405]
File - https://github.com/tungbq/devops-basic/blob/main/README.md
Typo found in the packer column:
![image](https://github.com/tungbq/devops-basic/assets/85242618/e8617c56-3670-4637-be94-b03f19d4cca7)

It should be `coming-soon`
Please help to fix this bug. Thanks

**NOTE:** This issue is opened for first timer contributor only.

**Comment by GDGouravDey** [comment]
I can fix this issue. You may assign me this.

**Comment by tungbq** [comment]
Sure @GDGouravDey. Thank you!
I've just assigned this to you. Welcome to this repository.

**Comment by GDGouravDey** [comment]
So, I have made the necessary changes in README.md and it is successfully reflecting on my branch. Should I do a PR or do I need to run tests?

![Screenshot 2024-01-06 124725](https://github.com/tungbq/devops-basic/assets/117531461/9c877935-a31a-4c70-9d03-638fa4744b80)
[Screenshot of the Result]

**Comment by tungbq** [comment]
Yeah, for this task, you could open the PR without testing. And I will review it.

**Comment by tungbq** [comment]
@all-contributors please add @GDGouravDey as code
