### ISSUE TITLE
[shell] Keep the shell folder clean

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#47]
For now, under https://github.com/tungbq/devops-basic/tree/main/shell we have some txt files using as examples, to keep the shell folder clean, we can:
- Create a new `data` folder under `shell `
- Move all *.txt files to `data` folder (for example [grep_example.txt](https://github.com/tungbq/devops-basic/blob/main/shell/grep_example.txt))
- Update related scripts that use these txt files to use the new location `shell/data/*.txt`
- Ensure no breakage in all current *.sh scripts of `shell `folder

**Comment by tungbq** [comment]
This needs #29 to be competed first

**Comment by thesilentline** [comment]
I am interested to fix this issue can you assign me @tungbq

**Comment by tungbq** [comment]
Sure! Assigned to you @thesilentline
