### ISSUE TITLE
coding: add `man-running` icon to the status of coding topic

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#472]
Add 🏃icon next to (in-progress) of coding column:
![image](https://github.com/tungbq/devops-basic/assets/85242618/beccc70a-c05b-468e-aa3d-4ca787e895d3)
https://github.com/tungbq/devops-basic/blob/main/README.md

**Comment by GDGouravDey** [comment]
Fixed this and sent a PR.
