### ISSUE TITLE
doc: broken link in `python` topic

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#473]
In: https://github.com/tungbq/devops-basic/tree/main/topics/python
![image](https://github.com/tungbq/devops-basic/assets/85242618/a963eb33-e130-4f85-acc1-befc6c16eb08)
(https://github.com/tungbq/devops-basic/blob/main/topics/python/helloworld/helloworld.py -> not found)
Please check and fix this:

**Comment by GDGouravDey** [comment]
Just did a PR that fixes this Issue, by changing the link address.
