### ISSUE TITLE
doc: remove the `book` icon from AWS topic column

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#487]
Remove the `book` icon from AWS topic column
File location: https://github.com/tungbq/devops-basic/blob/main/README.md
![image](https://github.com/tungbq/devops-basic/assets/85242618/eae421aa-8e37-407f-b9ca-51267eb60a5c)

**Comment by payneInTheBrian** [comment]
I sent a pr, please let me know if I need to modify anything.

**Comment by tungbq** [comment]
Thank you @payneInTheBrian
