### ISSUE TITLE
microservices/docs: Add `Azure-Samples/aks-store-demo` URL to the topic

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#501]
Update file https://github.com/tungbq/devops-basic/blob/main/topics/microservices/README.md:
- Add Sample microservices app for AKS demos link to https://github.com/Azure-Samples/aks-store-demo/tree/main

**Comment by payneInTheBrian** [comment]
i can hop on this

**Comment by tungbq** [comment]
> i can hop on this

Thank you @payneInTheBrian for your contributions to this repository
