### ISSUE TITLE
gitlab-ci: Adjust the heading format of Gitlab CI content

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#523]
https://github.com/tungbq/devops-basic/tree/main/topics/gitlabci#basics-of-gitlab-ci
Incorrect heading of `Basics of Gitlab CI`
This should be updated to be the same heading as https://github.com/tungbq/devops-basic/tree/main/topics/gitlabci#installation

**Comment by payneInTheBrian** [comment]
I can get on this

**Comment by tungbq** [comment]
Thank you @payneInTheBrian for your great contribution!
