### ISSUE TITLE
Create new `CODEOWNERS` file for devops-basic repository

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#53]
See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file
Task:
- [ ] Create new `CODEOWNERS` file
- [ ] Add `*    @tungbq ` to the newly created file
- [ ] Open the PR and waiting for merge
- [ ] Done! <3

**Comment by dcompanykrish** [comment]
I've reviewed your pull request and noticed that you have already added a CODEOWNERS file to the repository. This is great!
The CODEOWNERS file is now active. You are now the code owner for all files in the repository.
Please find the screenshot and close the issue #310 
![image](https://github.com/tungbq/devops-basic/assets/99336923/3c85487a-2c94-4efa-8083-88b4a38b9415)
