### ISSUE TITLE
Create new README.md file for ansible

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#58]
Tasks:
- Create new README.md file under https://github.com/tungbq/devops-basic/tree/main/ansible
- Then add following content:
```
Install Ansible
- Follow this guide: https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible
```

**Comment by akj2018** [comment]
Hi, I would like to take this issue. Please assign it to me.
Thank you

**Comment by tungbq** [comment]
Thanks @akj2018 assigned to you

**Comment by tungbq** [comment]
Done via #60. Thanks @akj2018
