### ISSUE TITLE
[github action] Add a github workflow to run shell script under `shell` folder

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#66]
Create new workflow under [.github/workflows](https://github.com/tungbq/devops-basic/tree/main/.github/workflows):
- Name it as `run-shell.yml` (or you can propose a better name)
- Checkout the code of this repository
- Execute the script https://github.com/tungbq/devops-basic/blob/main/shell/basic.sh
- The workflow needs to be run on every PR

**Comment by khanumar03** [comment]
i am working on it

**Comment by tungbq** [comment]
Thanks, assigning it to you @khanumar03

**Comment by khanumar03** [comment]
>hey thank you ,  is your  lf crlf issue fix i commented on  that please me know its fix  or  not @khanumar03

**Comment by tungbq** [comment]
> >hey thank you ,  is your  lf crlf issue fix i commented on  that please me know its fix  or  not @khanumar03
> 
> 
> 
> 

Sure, i'm out of office now! Will check and let u know soon. Thanks for your analysis

**Comment by khanumar03** [comment]
hey  is my PR work ?
