### ISSUE TITLE
feat: Create CODEOWNERS file

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#74]
Create new CODEOWNERS file under root path of this repo
Then add below line into the new file:
`* @tungbq`
Find more info at: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by Xzm27** [comment]
Apologies, made a mistake in the first pull request.

**Comment by bloemenk** [comment]
Hello,
I would like to offer my help for this issue if help is still wanted :)

Best regards,

Koen

**Comment by tungbq** [comment]
> Hello, I would like to offer my help for this issue if help is still wanted :)
> 
> Best regards,
> 
> Koen

Thanks @bloemenk for your interest, the issue has been resolved by @Xzm27 
You can find other issues at: https://github.com/tungbq/devops-basic/labels/good%20first%20issue
