### ISSUE TITLE
docs: Remove extra colon in README.md

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#85]
Remove some extra colon in https://github.com/tungbq/devops-basic/blob/main/README.md
![image](https://github.com/tungbq/devops-basic/assets/85242618/43b16f6d-5e61-41a5-88ec-d07be3437761)

**Comment by SaketKaswa20** [comment]
I don't think, that's actually an issue! It's looking good already.

**Comment by tungbq** [comment]
> I don't think, that's actually an issue! It's looking good already.

Yes @SaketKaswa20 not seems like a bug. But I just wanna align them with the others section in same format

**Comment by SaketKaswa20** [comment]
Ok, assign me this please, I'll do it.

**Comment by tungbq** [comment]
> Ok, assign me this please, I'll do it.

Thanks! assigned to you
